#  <span style="color:darkblue"> Linear Algebraic Systems </span>

<hr style="border:6px solid black"> </hr>

# <span style="color:darkblue"> Learning Objectives </span>

### *Setting up a linear system*
- Be able to distinguish a linear system from a nonlinear system.
- Learn to write a linear system in a matrix-vector format.
- Input a linear system into a program
- Write applicable engineering models in a linear format.

### *Characterizing linear systems*
- Determine the bandwidth(s) of the linear system.*
- Determine if a linear system has a unique solution.
- Will solving a linear system provide a meaningful result (is it well-posed).

### *Solving a linear system*
- Solve a linear system by Gauss-Elimination
- Solve a linear system by LU factorizations.
- State when numerical errors occur may occur in Gauss-Elimination and how to resolve them.\*
- Be able to state some conditions for the convergence of Jacobi and Gauss-Siedel methods.\*

\*Not covered in tutorial.

<hr style="border:6px solid black"> </hr>

# <span style="color:darkblue">  Relevance </span> 

It would be only a slight overstatement to say that linear algebra underlies all modern numerical algorithms to one degree or another. Even software which specifically addresses nonlinear or complicated forms will often make use of linear algebra in a myriad of subroutines. In essence, many complicated problems can be reduced to repeated formulating and solving linear systems. 

<hr style="border:2px solid gray"> </hr>

# <span style="color:darkblue"> Chlorination of Benzene </span>

Monochlorobenzene is a high boiling point solvent used in many industrial applications ranging from the manufacture of [dyes](https://patentimages.storage.googleapis.com/76/55/12/31756682f755c5/US6013811.pdf), [plastic and rubber processing](https://patentimages.storage.googleapis.com/66/c8/e1/69918f557fbd35/US8563079.pdf), [paints](https://patentimages.storage.googleapis.com/28/17/a7/a40e46f75806cf/US9062206.pdf), and [waxes](https://patents.google.com/patent/US3999960A/en). Approximately, [$1 billion](https://www.prnewswire.com/news-releases/global-chlorobenzene-industry-300939916.html) worth of this solvent are used per year. It is [produced by combining chlorine with benzene](https://onlinelibrary.wiley.com/doi/abs/10.1002/14356007.o06_o03) in the presence of a Lewis acid catalyst such as Ferric Chloride FeCl<sub>3</sub> or Anhydrous Aluminum Chloride AlCl<sub>3</sub>. When benzene and chlorine are mixed two key reactions occur: <b>(1)</b> the chlorination of benzene and <b>(2)</b> the secondary undesirable chlorination of the resulting monochlorobenzene. Product purity is ensured by performing a series of separation steps after the initial reaction and reagant usage is reduced by including a recycle loop. 

<div class="alert alert-block alert-info">
<b>Objective:</b> A large customer order has been placed for monochlorobenzene that needs to be fulfilled on a tight timeline. The small chemical company you work for has occasionally produced this solvent in the past and has an existing 6m<sup>3</sup> continuously stirred tank reactor (CSTR) that will need to be repurposed to produce 25kmol/h monochlorobenzene. Moreover, there isn't sufficient development time available to attempt to improve the processing conditions for the reactor or separators. As a result, you'll need to use the documented process conditions for the reactor and separators which means supplying to the first separator an effluent consisting of 90% benzene, 7% monochlorobenzene, and 3% dichlorobenzene by mole. We need to determine the recycle flow rates and reaction rates required needed to achieve the desired rate at which monochlorobenzene need to be produced.   
</div>

Denote benzene as (<b>A</b>), monochlorobenzene as (<b>B</b>), and dichlorobenzene as (<b>C</b>). The mole fraction of species <b>A</b> in stream <b>S1</b> is denote by <b>y</b><sub><b>1,A</b></sub> and the molar flowrate <b>F</b> [kmol/h] for stream <b>S1</b> is denoted <b>F1</b>.

- The feed stream is composed entirely of A and Cl<sub>2</sub>.
- An excess amount of Cl<sub>2</sub> is provided and HCl removal can be assumed to be trivial. So it's reasonable exclude it from our design considerations. Moreover, this means the reactions which take place in the reactor vessel can be simplified to <b>A</b> &rarr; <b>B</b> (at rate <b>r<sub>1</sub></b> [kmol/h]) and <b>B</b> &rarr; <b>C</b> (at rate <b>r<sub>2</sub></b> [kmol/h]).

<img src="Monochlorobenzene.png" width="800">

# <span style="color:darkblue"> Variables and Mass Balances </span>

For streams containing only a pure substance, we need only keep track of the total flow rate. Enumerating each quantity in the model is given by $F_1$, $F_2$, $F_3$, $F_4$, $F_5$, $F_6$, $F_7$, $y_{3,A}$, $y_{3,B}$, $y_{3,C}$, $y_{4,B}$, $y_{4,C}$, $r_1$, $r_2$, and $\nu$. Five of these are specified (e.g. these are **parameters** with fixed values). This leaves ten degrees of freedom associated with a variable. We'll now need to write out the equations which govern the system (physical laws, equipment specifications, and performance specifications). We'll start with writing the mass balances over each unit operation.  

<b>Mixer</b> (Overall Mass Balance): 

\begin{align}
    F_1 + F_7 - F_2 &= 0
\end{align}

<b>Reactor</b> (Individual Component Mass Balances):

\begin{align}
    F_2 - r_1\nu - y_{3,A}F_3 &= 0 \\
    (r_1 - r_2)\nu + y_{3,B}F_3 &= 0 \\
    r_2\nu  - y_{3,C}F_3 &= 0
\end{align}

<b>Separator #1</b> (Individual Component Mass Balances):

\begin{align}
    F_3 - F_4 - F_7 &= 0 \\
    y_{3,B}F_3 - y_{4,B}F_4 &= 0 \\
    y_{3,C}F_3 - y_{4,C}F_4 &= 0
\end{align}

<b>Separator #2</b> (Individual Component Mass Balances):

\begin{align}
    F_4 - F_5 - F_6 &= 0 \\
    y_{4,B}F_4 - F_5 &= 0
\end{align}

In order to write these equations in a matrix-vector form: we'll first need to associate each variable (excluding **parameters**) in the model with a component in a vector of variables, $\mathbf{x}$. 

\begin{align}
    \mathbf{x} = (F_1, F_2, F_3, F_4, F_6, F_7, y_{4,B}, y_{4,C}, r_1, r_2)
\end{align}

So, $x_2 = F_2$, $x_3 = F_3$ and so on until we have $x_{10} = r_2$.  

<div class="alert alert-block alert-info">
Now, take a minute to inspect the model and categorize the system of equations.      
</div>

The 2nd and 3rd equations for Separator #1 as well as the 2nd equation in Separator #2 contain the expressions $y_{4,B}F_4$ and $y_{4,C}F_4$. These terms consist of two variables being multiplied by one another (a <b>bilinear term</b>) which is one of simplest commonly encountered nonlinear term. All other expressions consist of addition, subtraction, and the multiplication of a parameter by a variable. So this system of equations is nonlinear but would be linear if we ommitted the expressions: $y_{4,B}F_4$ and $y_{4,C}F_4$.

<div class="alert alert-block alert-info">
It's often useful to reformulate a model (algebraicly rearrange and potentially introduce new variables) to arrive at a more easily solvable form.       
</div>

We'll start by introducing two new variables: the molar flowrates $F_{4,B}$ and $F_{4,C}$ defined as by

\begin{align}
    F_{4,B} = y_{4,B}F_4 \\
    F_{4,C} = y_{4,C}F_4
\end{align}

We can then write an additional equation for the molar flowrates of <b>S4</b>:

<b>Molar flowrate expressions for S4</b>:

\begin{align}
    F_{4,B} + F_{4,C} &= F_4
\end{align}

Next, we'll introduce the variables: $F_{3,A}$, $F_{3,B}$, and $F_{3,C}$ defined as:

\begin{align}
    F_{3,A} = y_{3,A}F_3 \\
    F_{3,B} = y_{3,B}F_3 \\
    F_{3,C} = y_{3,C}F_3
\end{align}

We can then write an additional equation for the molar flowrates of <b>S3</b>:

<b>Molar flowrate expressions for S3</b>:

\begin{align}
F_{3,A} + F_{3,B} + F_{3,C} = F_3
\end{align}

We can then rearrange the mass balances for the Reactor, Separator #1, and Separator #2.

<b>Reactor</b> (Individual Component Mass Balances):

\begin{align}
    F_2 - r_1\nu - F_{3,A} &= 0 \\
    (r_1 - r_2)\nu + F_{3,B} &= 0 \\
    r_2\nu  - F_{3,C} &= 0
\end{align}

<b>Reformulated Separator #1 Mass Balances</b>:

\begin{align}
    F_3 - F_4 - F_7 &= 0 \\
    F_{3,B} - F_{4,B} &= 0 \\
    F_{3,C} - F_{4,C} &= 0
\end{align}

<b>Reformulated Separator #2 Mass Balances</b>:

\begin{align}
    F_4 - F_5 - F_6 &= 0 \\
    F_{4,B} - F_5 &= 0
\end{align}

\begin{align}
    \mathbf{x'} = (F_1, F_2, F_{3,A}, F_{3,B}, F_{3,C}, F_3, F_{4,B}, F_{4,C}, F_4, F_6, F_7, r_1, r_2)
\end{align}


<div class="alert alert-block alert-warning">
<b>INTERACTIVE!</b> Now we enter the above linear equation, <b>Mx' = b </b> in matrix-vector form.
</div>

In [19]:
# Define the Mx' = b linear system


# Define storage for linear system
M = zeros(13,13)    # Makes an 2d array of size 13-by-13. This array has 13 rows and 13 columns.
b = zeros(13)       # Makes a column vector of size 10. A vector with 13 rows and 1 column.

# Input parameters
y3A = 0.90      # effluent benzene concentration of reactor
y3B = 0.07      # effluent monochlorobenzene concentration of reactor
y3C = 0.03      # effluent dichlorobenzene concentration of reactor
V = 6           # reactor volume
F_5 = 25.0      # flow rate of monochlorobenzene required

### MASS BALANCE (MIXER) ###

# fills in the first row
M[1,1] = 1.0        # Set the matrix M's entry in the first row and first column to 1
M[1,2] = -1.0       # Set the matrix M's entry in the first row and second column to -1
M[1,11] = 1.0       # Set the matrix M's entry in the first row and eighth column to 1

# b[1] and all other entries of M in row #1, so no need to change these values

M[2,2] = 1.0  # reactor - equation #1       
M[2,3] = -1.0
M[2,12] = -V

M[3,4] = 1.0  # reactor - equation #2        
M[3,12] = -V
M[3,13] = V

M[4,5] = -1.0 # reactor - equation #3       
M[4,13] = V

M[10,8] = 1.0  # stream 4 balance     
M[10,9] = -1.0
M[10,7] = 1.0

M[11,3] = 1.0  # stream 3 balance #1      
M[11,4] = 1.0
M[11,5] = 1.0
M[11,6] = -1.0

M[12,3] = 1.0  # stream 3 balance #2
M[12,6] = -y3A

M[13,4] = 1.0  # stream 4 balance #3
M[13,6] = -y3B

### SEPARATOR #1 & 2  - MASS BALANCES ###

# FILL IN THE REST BELOW HERE IN ROWS 5 to 9 of M!!!!!!!!

-0.07

In [20]:
# Run this to display the input matrix and vector
display("This Matrix (M) is  ") 
display(M)
display("The r.h.s vector (b) is  ") 
display(b)
x =  M\b
display(x)

"This Matrix (M) is  "

13×13 Array{Float64,2}:
 1.0  -1.0   0.0  0.0   0.0   0.0    0.0   0.0   0.0   0.0   1.0   0.0  0.0
 0.0   1.0  -1.0  0.0   0.0   0.0    0.0   0.0   0.0   0.0   0.0  -6.0  0.0
 0.0   0.0   0.0  1.0   0.0   0.0    0.0   0.0   0.0   0.0   0.0  -6.0  6.0
 0.0   0.0   0.0  0.0  -1.0   0.0    0.0   0.0   0.0   0.0   0.0   0.0  6.0
 0.0   0.0   0.0  0.0   0.0   1.0    0.0   0.0  -1.0   0.0  -1.0   0.0  0.0
 0.0   0.0   0.0  1.0   0.0   0.0   -1.0   0.0   0.0   0.0   0.0   0.0  0.0
 0.0   0.0   0.0  0.0   1.0   0.0    0.0  -1.0   0.0   0.0   0.0   0.0  0.0
 0.0   0.0   0.0  0.0   0.0   0.0    0.0   0.0   1.0  -1.0   0.0   0.0  0.0
 0.0   0.0   0.0  0.0   0.0   0.0    0.0   1.0   0.0   0.0   0.0   0.0  0.0
 0.0   0.0   0.0  0.0   0.0   0.0    1.0   1.0  -1.0   0.0   0.0   0.0  0.0
 0.0   0.0   1.0  1.0   1.0  -1.0    0.0   0.0   0.0   0.0   0.0   0.0  0.0
 0.0   0.0   1.0  0.0   0.0  -0.9    0.0   0.0   0.0   0.0   0.0   0.0  0.0
 0.0   0.0   0.0  1.0   0.0  -0.07   0.0   0.0   0.0   0.0   0.0

"The r.h.s vector (b) is  "

13-element Array{Float64,1}:
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
 25.0
 25.0
  0.0
  0.0
  0.0
  0.0

13-element Array{Float64,1}:
  83.33333333333337 
 833.3333333333339  
 750.0000000000006  
  58.33333333333337 
  25.0              
 833.3333333333339  
  58.33333333333337 
  25.0              
  83.33333333333337 
  58.33333333333337 
 750.0000000000006  
  13.888888888888896
   4.166666666666667

# <span style="color:darkblue"> Existence and Uniqueness of the Solution </span>

Now that the linear system has been formulated, let's check to see whether the system has a solution. For a square matrix <b>M</b>, <b>M</b> system is <b>invertible</b>

<div class="alert alert-block alert-warning">
    <b>INTERACTIVE!</b> Make use of the function <b>det</b> to check see if matrix <b>M</b> is invertible. Does the linear equation <b>Mx = b</b> have a unique solution? 
</div>

In [21]:
using LinearAlgebra: det

# FILL IN THE REST BELOW HERE
det(M)

-1.0799999999999992

# <span style="color:darkblue">  Well-posed problems and the Condition Number </span>

While a linear system, `Mx = b`, may have a unique solution, we also seek to understand whether using a particular algorithm to solve `Mx = b` will yeild an accurate solution. We often don't know `M` or `b` exactly. As a consequence, solutions which vary greatly when `M` or `b` are slightly perturbed may be suspect. This is generally assessed by evaluating the **condition number** of a linear system and is defined as: $\text{cond}(M) \equiv ||M|| \times ||M^{-1}||$. A derivation of this is given in section 2.3.4 of Dorfman and Daoutidis, Numerical Methods with Chemical Engineering Applications which arrives at the following inequality:

$||\Delta x || \leq \text{cond}(M)\bigg(\frac{|| \Delta b || || x ||}{|| b ||}\bigg)$

For a fixed condition number, $\text{cond}(M)$, solution $x$, and $b$ if we slightly perturb $b$ by $\Delta b$ then $x$ may change by at most an amount proportional to the condition number. Another way of interpreting this is by applying the following rule of thumb: the condition number $\kappa$ means that the method looses $\log_{10}{\kappa}$ of accuracy relative to rounding error.

If an application leads to an ill-posed problem (values of **M** and **b** may be known to very high precision), there are a multitude of ways this may be dealt with. This most common and often most robust approach is to apply a [**preconditioner**](http://www.mathcs.emory.edu/~benzi/Web_papers/survey.pdf). That is we find an appropriate matrix **Y** and multiply both sides of the original linear system to create an equivalent new linear system, `(YM)x = (Yb)`, which has a lower condition number. We can then solve the equivalent modified system. 

<div class="alert alert-block alert-warning">
<b>INTERACTIVE!</b> Make use of the function <b>cond</b> to compute the condition number using the $L^2$-norm. Is the matrix <b>A</b> well-conditioned? 
</div>

In [22]:
using LinearAlgebra: cond

# FILL IN THE REST BELOW HERE

1494.7023893088221

# <span style="color:darkblue">  Solving the linear equation with Gauss Elimination </span>

Now let's write a quick script to solve <b>Mx = b</b>. We'll do this in three steps. Defining a function to perform forward elimination, a function to back substitution, and lastly a main function to perform each of the prior functions in sequence.

In [ ]:
function forward_elimination!(M,b,n)
    
    for k = 1:(n - 1)
        for i = (k + 1):n
            m = M[i,k]/M[k,k]
            for j = (k + 1):n
                M[i,j] = M[i,j] - m*M[k,j]
            end
            b[i] = b[i] - m*b[k]
        end
    end
    
    return nothing
end

<div class="alert alert-block alert-info">
<b>Comment</b>: Note that while <b>M</b>, <b>b</b> are used in prior cells these variables don't interfere in the definition of <b>forward_elimination!</b>. The variables listed in the argument of <b>forward_elimination!</b>, that is (<b>M</b>,<b>x</b>,<b>b</b>,<b>n</b>), are evaluated in local scope when <b>forward_elimination!</b> is called.
</div>

<div class="alert alert-block alert-warning">
<b>INTERACTIVE!</b> The overall gauss elimination function is defined below. You just need to finish coding the <b>back_substitution!</b> function.
</div>

In [ ]:
function back_substitution!(M,x,b,n)
    
    # FILL IN THE REST BELOW HERE
    
    return nothing
end

In [2]:
function Gauss_Elimination!(M, b)
    n = length(b)
    x = zeros(n)
    
    forward_elimination!(M,b,n)
    back_substitution!(M,x,b,n)  
   
    return x
end

# Runs a Gauss elimination routine using Mx = b has inputs
x = Gauss_Elimination!(M, b)

display("The solution via Gauss elimination is "); 
display(x)

UndefVarError: UndefVarError: M not defined

# <span style="color:darkblue">  Solving with an LU factorization </span>

<div class="alert alert-block alert-warning">
<b>INTERACTIVE!</b> Run the following snippet of code to solve the linear system using LU factorization to solve the linear system.
</div>

In [29]:
using LinearAlgebra: lu

lu_fact = lu(M) # performs an LU factorization of M. Note that pivot = Val(false)
                # means that the LU factorization is performed without pivoting
                # (otherwise a permutation matrix describing the pivots is computed as well)

y = lu_fact.L\b                   # solve Ly = b for y
x = lu_fact.U\y                   # solve Ux = y for x

display("The solution via LU factorization is "); 
display(x)

"The solution via LU factorization is "

13-element Array{Float64,1}:
  83.33333333333337 
 833.3333333333339  
 750.0000000000006  
  58.33333333333337 
  24.999999999999996
 833.3333333333339  
  58.33333333333337 
  25.0              
  83.33333333333337 
  58.33333333333337 
 750.0000000000006  
  13.888888888888896
   4.166666666666666

<hr style="border:6px solid black"> </hr>

# <span style="color:darkblue">  Questions for reflection </span> 

- What varieties of problems may result in a banded matrix?
- What does it mean that an iterative method converged? 
- When is an absolute or relative convergence criteria preferable?
- When is solving by one method versus another preferable (e.g. Banded Gauss-Elimination versus Gauss-Siedel)?